### ISSUE TITLE
CoordAmap 是private的

### ISSUE THREAD

**Issue by kiritokun07** [Phantom0103/elem-open-sdk#2]
https://github.com/Phantom0103/elem-open-sdk/blob/main/src/main/java/elem/retail/dto/order/OrderGetResult.java#L361

Coord是public的，可以拿到这个参数，但CoordAmap 是private的，虽然有@Getter和@Setter，但ide还是报错了

**Comment by Phantom0103** [comment]
这个已经改了，更新2.5.6

**Comment by kiritokun07** [comment]
3q，我在2.5.4发现的这个问题，忘记报版本号了

**Comment by kiritokun07** [comment]
阿里云maven版本停留在2.5.4了，请问哪里可以找到最新版
https://developer.aliyun.com/mvn/search
```
<dependency>
    <groupId>io.github.phantom0103</groupId>
    <artifactId>elem-open-sdk</artifactId>
    <version>2.5.4</version>
</dependency>
```

**Comment by Phantom0103** [comment]
最新版2.5.6已经提交到maven中央仓库，直接改下你的pom文件里面的版本号就可以，mvn仓库可能会有点延迟
